AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  OutputBucketName:
    Type: String
    Description: Name of the S3 bucket to store query results

Resources:
  AthenaQueryRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AthenaQueryRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: AthenaQueryRolePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: AllowAthenaQuery
                Effect: Allow
                Action:
                  - "athena:StartQueryExecution"
                  - "athena:GetQueryExecution"
                  - "athena:GetQueryResults"
                Resource: "*"
              - Sid: AllowGlueAccess
                Effect: Allow
                Action:
                  - "glue:GetTable"
                  - "glue:GetPartitions"
                Resource:
                  - !Sub "arn:aws:glue:${AWS::Region}:955609534476:database/cid_cur"
                  - !Sub "arn:aws:glue:${AWS::Region}:955609534476:catalog"
                  - !Sub "arn:aws:glue:${AWS::Region}:955609534476:table/cid_cur/cur"
              - Sid: AllowS3Access
                Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:PutObject"
                  - "s3:GetBucketLocation"
                  - "s3:*"
                Resource:
                  - !Sub "arn:aws:s3:::${OutputBucketName}/*"
                  - !Sub "arn:aws:s3:::${OutputBucketName}"
                  - "arn:aws:s3:::cid-955609534476-shared"
                  - "arn:aws:s3:::cid-955609534476-shared/*"
  AthenaQueryLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: AthenaQueryLambda
      Handler: athena_query.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Timeout: 300
      Environment:
        Variables:
          OUTPUT_BUCKET_NAME: !Ref OutputBucketName
      Role: !GetAtt AthenaQueryRole.Arn

Outputs:
  OutputBucketName:
    Value: !Ref OutputBucketName
